application: uwm-transit-tracker
version: 1
runtime: python27
api_version: 1
threadsafe: false

handlers:
- url: /css
  static_dir: css
 
- url: /font
  static_dir: font

- url: /ico
  static_dir: ico
  
- url: /js
  static_dir: js
  
- url: /json
  static_dir: json
  application_readable: true
 
- url: /.*
  script: main.py
  
libraries:
- name: jinja2
  version: latest